// Generated by CoffeeScript 1.10.0
(function() {
  var EventEmitter, Header, Parser, fs, iconv,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('events').EventEmitter;

  Header = require('./header');

  fs = require('fs');

  iconv = require('iconv-lite');

  iconv.skipDecodeWarning = true;

  Parser = (function(superClass) {
    extend(Parser, superClass);

    function Parser(filename, encoding) {
      this.filename = filename;
      this.encoding = encoding != null ? encoding : 'utf-8';
      this.parseField = bind(this.parseField, this);
      this.parseRecord = bind(this.parseRecord, this);
      this.parse = bind(this.parse, this);
    }

    Parser.prototype.parse = function() {
      this.emit('start', this);
      this.header = new Header(this.filename);
      this.header.parse((function(_this) {
        return function(err) {
          var sequenceNumber;
          _this.emit('header', _this.header);
          sequenceNumber = 0;
          return fs.readFile(_this.filename, function(err, buffer) {
            var loc;
            if (err) {
              throw err;
            }
            loc = _this.header.start;
            while (loc < (_this.header.start + _this.header.numberOfRecords * _this.header.recordLength) && loc < buffer.length) {
              _this.emit('record', _this.parseRecord(++sequenceNumber, buffer.slice(loc, loc += _this.header.recordLength)));
            }
            return _this.emit('end', _this);
          });
        };
      })(this));
      return this;
    };

    Parser.prototype.parseRecord = function(sequenceNumber, buffer) {
      var field, fn, i, len, loc, record, ref;
      record = {
        '@sequenceNumber': sequenceNumber,
        '@deleted': (buffer.slice(0, 1))[0] !== 32
      };
      loc = 1;
      ref = this.header.fields;
      fn = (function(_this) {
        return function(field) {
          return record[field.name] = _this.parseField(field, buffer.slice(loc, loc += field.length));
        };
      })(this);
      for (i = 0, len = ref.length; i < len; i++) {
        field = ref[i];
        fn(field);
      }
      return record;
    };

    Parser.prototype.parseField = function(field, buffer) {
      var value;
      value = (iconv.decode(buffer, this.encoding)).trim();
      if (field.type === 'N') {
        value = parseFloat(value);
      }
      return value;
    };

    return Parser;

  })(EventEmitter);

  module.exports = Parser;

}).call(this);
